# Copyright (C) 2024 ETAS and other Eclipse Foundation contributors
# 
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: 'quevee'
description: 'QUality-EVEnt Engine for collecting quality-related build and release artefacts'
branding:
  icon: 'award'
  color: 'green'
inputs:
  release_url:
    description: 'URL of the release this manifest refers to'
    required: false
  artefacts_readme:
    description: 'Comma-separated list of URLs of READMEs'
    required: false
  artefacts_requirements:
    description: 'Comma-separated list of URLs of requirement files'
    required: false
  artefacts_testing:
    description: 'Comma-separated list of URLs of test results'
    required: false
  artefacts_documentation:
    description: 'Comma-separated list of URLs of documentation artefacts'
    required: false
  artefacts_coding_guidelines:
    description: 'Comma-separated list of URLs of coding guidelines documents'
    required: false
  artefacts_release_process:
    description: 'Comma-separated list of URLs of release process information'
    required: false
outputs:
  manifest_file:
    description: 'Process artefacts manifest file name'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.release_url }}
    - ${{ inputs.artefacts_readme }}
    - ${{ inputs.artefacts_requirements }}
    - ${{ inputs.artefacts_testing }}
    - ${{ inputs.artefacts_documentation }}
    - ${{ inputs.artefacts_coding_guidelines }}
    - ${{ inputs.artefacts_release_process }}
