on:
  push:
    tags:
      - v*
concurrency:
  group: "release-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:
  quality_artefacts_job:
    name: A job to collect quality artefacts
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create release
        uses: softprops/action-gh-release@v2
        id: create_release
      - name: Show release URL
        run: |
          echo ${{ steps.create_release.outputs.url }}
      # Call the quevee gh action to create the manifest file for SDV maturity assessment.
      - name: Collect quality artefacts
        uses: eclipse-dash/quevee
        id: quevee
        with:
          release_url: ${{ steps.create_release.outputs.url }}
          artefacts_readme: README.md
          artefacts_requirements: docs/requirements.md
          artefacts_testing: tests/test_report.md
          artefacts_documentation: docs/getting_started/README.md
          artefacts_coding_guidelines: docs/coding_guidelines.md
          artefacts_release_process: https://example.org/docs/my_release_process.md
      - name: Upload quality manifest to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.quevee.outputs.manifest_file }}
          tag: ${{ github.ref }}
